baseURL = "https://mtorials-test.netlify.app/"
languageCode = "en-us"
title = "mt32.net"
theme = "mt32"

[params]
  description = "The mt32.net blog!"
  disclamer = "Copyright mtorials.de @2020"
  github = "https://github.com/mtorials"
  youtube = "https://www.youtube.com/channel/UCe3IgjqCm5YZ6YSeAkohnNA"
  twitter = "https://twitter.com/universumgames"


[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "solarized-dark256"
    tabWidth = 4
