baseURL = "https://mt32.netlify.app/"
languageCode = "en-us"
title = "mt32.net"
theme = "mt32"

[params]
  description = "The mt32.net blog!"
  disclamer = "The content of this website is licensed under the CC BY-NC-SA 4.0 license. No warrenties apply."
  license = "https://creativecommons.org/licenses/by-nc-sa/4.0/"
  github = "https://github.com/mtorials"
  youtube = "https://www.youtube.com/channel/UCe3IgjqCm5YZ6YSeAkohnNA"
  twitter = "https://twitter.com/universumgames"


[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "solarized-dark256"
    tabWidth = 4
